const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: " USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: " USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_PATIENT_SUCCESS: "FETCH_GENDER_PATIENT_SUCCESS",
  FETCH_GENDER_PATIENT_FAILED: "FETCH_GENDER_PATIENT_FAILED",

  BOOKING_PATIENT_APPOINTMENT_SUCCESS: "BOOKING_PATIENT_APPOINTMENT_SUCCESS",
  BOOKING_PATIENT_APPOINTMENT_FAILED: "BOOKING_PATIENT_APPOINTMENT_FAILED",

  ACTION_CLICK_BTN_FORGOT_PASSWORD_SUCCESS:
    "ACTION_CLICK_BTN_FORGOT_PASSWORD_SUCCESS",
  ACTION_CLICK_BTN_FORGOT_PASSWORD_FAILED:
    "ACTION_CLICK_BTN_FORGOT_PASSWORD_FAILED",

  VERIFY_RESET_PASSWORD_SUCCESS: "VERIFY_RESET_PASSWORD_SUCCESS",
  VERIFY_RESET_PASSWORD_FAILED: "VERIFY_RESET_PASSWORD_FAILED",

  //admin
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFO_SUCCESS",
  FETCH_REQUIRED_DOCTOR_INFO_FAILED: "FETCH_REQUIRED_DOCTOR_INFO_FAILED",

  //doctor
  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILED: "FETCH_TOP_DOCTOR_FAILED",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILED: "FETCH_ALL_DOCTOR_FAILED",

  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAILED: "SAVE_DETAIL_DOCTOR_FAILED",

  GET_DETAIL_DOCTOR_SUCCESS: "GET_DETAIL_DOCTOR_SUCCESS",
  GET_DETAIL_DOCTOR_FAILED: "GET_DETAIL_DOCTOR_FAILED",

  GET_DOCTOR_MARKDOWN_SUCCESS: "GET_DOCTOR_MARKDOWN_SUCCESS",
  GET_DOCTOR_MARKDOWN_FAILED: "GET_DOCTOR_MARKDOWN_FAILED",

  FETCH_ALLCODE_SCHEDULE_TIMES_SUCCESS: "FETCH_ALLCODE_SCHEDULE_TIMES_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_TIMES_FAILED: "FETCH_ALLCODE_SCHEDULE_TIMES_FAILED",

  SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS: "SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS",
  SAVE_BULK_SCHEDULE_DOCTOR_FAILED: "SAVE_BULK_SCHEDULE_DOCTOR_FAILED",

  DELETE_PAST_SCHEDULE_DOCTOR_SUCCESS: "DELETE_PAST_SCHEDULE_DOCTOR_SUCCESS",
  DELETE_PAST_SCHEDULE_DOCTOR_FAILED: "DELETE_PAST_SCHEDULE_DOCTOR_FAILED",

  //specialty
  CREATE_NEW_SPECIALTY_SUCCESS: "CREATE_NEW_SPECIALTY_SUCCESS",
  CREATE_NEW_SPECIALTY_FAILED: "CREATE_NEW_SPECIALTY_FAILED",

  FETCH_ALL_SPECIALTY_SUCCESS: "FETCH_ALL_SPECIALTY_SUCCESS",
  FETCH_ALL_SPECIALTY_FAILED: "FETCH_ALL_SPECIALTY_FAILED",

  //clinic
  CREATE_NEW_CLINIC_SUCCESS: "CREATE_NEW_CLINIC_SUCCESS",
  CREATE_NEW_CLINIC_FAILED: "CREATE_NEW_CLINIC_FAILED",

  FETCH_ALL_CLINIC_SUCCESS: "FETCH_ALL_CLINIC_SUCCESS",
  FETCH_ALL_CLINIC_FAILED: "FETCH_ALL_CLINIC_FAILED",
});

export default actionTypes;
